### ISSUE TITLE
Traceback (most recent call last):   File "yolo.py", line 157, in <module>     height, width = frame.shape[:2] AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by irvanseptiar** [iArunava/YOLOv3-Object-Detection-with-OpenCV#11]

**Comment by irvanseptiar** [comment]
Traceback (most recent call last):   File "yolo.py", line 157, in <module>     height, width = frame.shape[:2] AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by aryankrowser** [comment]
did you resolve the issue/

**Comment by aryankrowser** [comment]
did anyone find this solution?
